routes/backend.php
<?php

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');
Route::resource('image', 'Backend\ImageController');
Route::resource('video', 'Backend\VideoController');
Route::resource('press-release', 'Backend\EventController');
Route::resource('contacts', 'Backend\ContactController');
Route::resource('management', 'Backend\ManagementController');
Route::resource('expert', 'Backend\ExpertController');
Route::resource('institutional', 'Backend\InstitutionalController');
Route::resource('category', 'Backend\CategoryController');
Route::resource('blog', 'Backend\BlogController');
Route::resource('testimonial', 'Backend\TestimonialController');
Route::resource('slider', 'Backend\SliderController');
Route::resource('rating', 'Backend\RatingController');
Route::get('/rating/status/{id}','Backend\RatingController@statusChange')->name('rating.status.change');
Route::resource('service', 'Backend\ServiceController');
Route::resource('webinfo', 'Backend\WebInfoController');
Route::get('/career/info','Backend\WebInfoController@career')->name('webinfo.career');
Route::resource('career', 'Backend\CareerController');
Route::resource('career-applicant', 'Backend\CareerAppliesController');
Route::post('/career-applicant/status/','Backend\CareerAppliesController@statusUpdate')->name('career-applicant.status.change');
Route::post('/career/sort','Backend\CareerController@sort')->name('career.sort');
Route::get('/career/status/{id}','Backend\CareerController@statusChange')->name('career.status.change');
Route::get('/settings','Backend\WebInfoController@setting')->name('setting.change');

routes/frontend.php
<?php

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// redirect from register page to home page
Route::get('/admin', function () {
    return redirect('/admin/login');
});

Route::get('/run-migrate', function () {
    Artisan::call('migrate');
    return "Successfully migrated";

});
Route::get('/config-cache', function () {
    Artisan::command('logs:clear', function() {

        exec('rm ' . storage_path('logs/*.log'));

        $this->comment('Logs have been cleared!');

    })->describe('Clear log files');
    return "Successfully cleared logs";

});
Artisan::command('logs:clear', function() {

    exec('rm ' . storage_path('logs/*.log'));

    $this->comment('Logs have been cleared!');

})->describe('Clear log files');

Route::get('/clear-cache', function () {

    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('config:cache');
    Artisan::call('view:clear');
    return "Cache is cleared";
});
Route::get('/storage-link', function () {

    Artisan::call('storage:link');
    return "Storage is linked";
});


Route::get('/comming-soon', 'frontend\FrontendController@commingSoon')->name('frontend.comming.soon');
Route::get('/', 'frontend\FrontendController@index')->name('frontend.home');

/*about*/
Route::get('/about', 'frontend\FrontendController@about')->name('frontend.about');

/*services*/
Route::get('/services', 'frontend\FrontendController@service')->name('frontend.service');
Route::get('/service-detail/{id}', 'frontend\FrontendController@serviceDetail')->name('frontend.service-detail');

/*Rating*/
Route::get('/ratings', 'frontend\FrontendController@ratings')->name('frontend.ratings');
Route::get('/ratings/search', 'frontend\FrontendController@ratingsSearch')->name('frontend.ratingsSearch');
Route::get('/rating-details/{id}', 'frontend\FrontendController@ratingsDetails')->name('frontend.ratingsDetail');

/*Press Release*/
Route::get('/press-release', 'frontend\FrontendController@pressRelease')->name('frontend.pressRelease');
Route::get('/press-release-detail/{id}', 'frontend\FrontendController@pressReleaseDetail')->name('frontend.pressReleaseDetail');

/*Career*/
Route::get('/career', 'frontend\FrontendController@careers')->name('frontend.career');
Route::get('/career-details/{id}', 'frontend\FrontendController@careerDetail')->name('frontend.career.detail');
Route::get('/career-apply', 'frontend\FrontendController@careerApply')->name('frontend.career.apply');
Route::post('/career-apply', 'Backend\CareerAppliesController@store')->name('frontend.career.apply.new');

/*Contact*/
Route::get('/contact', 'frontend\FrontendController@contact')->name('frontend.contact');
Route::post('/contact', 'frontend\FrontendController@contactUs')->name('contact.us');


/*Fallback*/
Route::fallback(function() {
    return view('nopage');
});

resources/views/backend/partials/press-release/add.blade.php
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Add Press Release</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                    <form method="POST" action="{{route('press-release.store')}}" enctype="multipart/form-data">
                        {{csrf_field()}}
                        <div class="form-group">
                            <label for="exampleInputFile">Select File</label>
                            <input type="file" value="{{old('file')}}" name="file" accept="application/pdf,application/vnd.ms-excel" id="exampleInputFile" required>
                            <p class="help-block">File Must Be In PDF Format.</p>
                        </div>
                        <div class="form-group">
                            <label for="category">Subject</label>
                            <input type="text"value="{{old('author')}}" name="author" class="form-control" id="category" placeholder="Enter Subject" required>
                        </div>
                        <div class="form-group">
                            <label for="title">Press Release Title</label>
                            <input type="text" value="{{old('title')}}" name="title" class="form-control" id="title" placeholder="Enter Title" required>
                        </div>
                        <div class="form-group">
                            <label for="description">Press Release Description</label>
                            <textarea name="description" value="{{old('description')}}" class="form-control" id="description" cols="5" rows="10"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

resources/views/backend/partials/press-release/edit.blade.php
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Edit Press Release</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{route('press-release.update',['event'=>$event['id']])}}" enctype="multipart/form-data">
                    {{method_field('patch')}}
                    {{csrf_field()}}
                    <div class="form-group">
                        <label for="exampleInputFile">Select File</label>
                        <input type="file" name="file" accept="application/pdf,application/vnd.ms-excel" id="exampleInputFile">
                        <p class="help-block">File Must Be In PDF Format.</p>
                    </div>
                    <div class="form-group">
                            <label for="author">Subject</label>
                            <input type="text"value="{{$event['author_name']}}" name="author" class="form-control"  id="author" placeholder="Enter Subject" required>
                        </div>
                        <div class="form-group">
                            <label for="title">Press Release Title</label>
                            <input type="text" value="{{$event['title']}}" name="title" class="form-control" id="title" placeholder="Enter Title" required>
                        </div>
                        <div class="form-group">
                            <label for="description">Press Release Description</label>
                            <textarea name="description" class="form-control" id="description" cols="5" rows="10">{{$event['description']}}</textarea>
                        </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

resources/views/backend/partials/press-release/press-release.blade.php
@extends('backend.layouts.app')
@section('content')
    <div class="banner">
        <h2>
            <a href="/admin/home">Home</a>
            <i class="fa fa-angle-right"></i>
            <span>Press Release</span>
        </h2>
    </div>
    <!--//banner-->
    <!--faq-->
    <div class="blank">


        <div class="blank-page">

            <div class="grid_3 grid_5">
                <div class="bs-example2 bs-example-padded-bottom">
                    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#addModal">
                        Add Press Release
                    </button>
                </div>
                @include('backend.partials.press-release.add')
            </div>
            <table class="table" id="datatable">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">File</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($events as $event)
                    <tr>
                <td scope="row">{{$loop->iteration}}</td>
                        <td>
                            <div class="col-md">
                                <div class="gallery-img">
                                    <a target="_blank" href="{{asset('images/event/'.$event['image'])}}"><i class="fa fa-file-pdf-o make-large" aria-hidden="true"></i></a>

                                </div>
                            </div>
                        </td>
                        <td>{{$event['author_name']}}</td>
                        <td>{{$event['title']}}</td>
                        <td> @if(strlen($event['description'])>300)
                                {!! substr($event['description'],0,strpos($event['description'],".",300))!!}
                            @else
                                {!!$event['description']!!}
                            @endif</td>
                        <td><button data-toggle="modal" data-target="#editModal{{$event['id']}}">
                                <i class="fa fa-pencil-square text-primary fa-2x"></i>
                            </button>&ensp;&ensp;
                            <form action="{{ route('press-release.destroy', ['event'=>$event['id']]) }}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button onclick="return confirm('Are you sure you want to delete?')">  <i class="fa fa-trash text-danger fa-2x"></i></button>
                            </form>
                           </td>
                        <div class="modal fade" id="editModal{{$event['id']}}" tabindex="-1" role="dialog"
                             aria-labelledby="myModalLabel"
                             aria-hidden="true" style="display: none;">
                            @include('backend.partials.press-release.edit')
                        </div>

                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>

@endsection