routes/backend.php
<?php

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');
Route::resource('image', 'Backend\ImageController');
Route::resource('video', 'Backend\VideoController');
Route::resource('press-release', 'Backend\EventController');
Route::resource('contacts', 'Backend\ContactController');
Route::resource('management', 'Backend\ManagementController');
Route::resource('expert', 'Backend\ExpertController');
Route::resource('institutional', 'Backend\InstitutionalController');
Route::resource('category', 'Backend\CategoryController');
Route::resource('blog', 'Backend\BlogController');
Route::resource('testimonial', 'Backend\TestimonialController');
Route::resource('slider', 'Backend\SliderController');
Route::resource('rating', 'Backend\RatingController');
Route::get('/rating/status/{id}','Backend\RatingController@statusChange')->name('rating.status.change');
Route::resource('service', 'Backend\ServiceController');
Route::resource('webinfo', 'Backend\WebInfoController');
Route::get('/career/info','Backend\WebInfoController@career')->name('webinfo.career');
Route::resource('career', 'Backend\CareerController');
Route::resource('career-applicant', 'Backend\CareerAppliesController');
Route::post('/career-applicant/status/','Backend\CareerAppliesController@statusUpdate')->name('career-applicant.status.change');
Route::post('/career/sort','Backend\CareerController@sort')->name('career.sort');
Route::get('/career/status/{id}','Backend\CareerController@statusChange')->name('career.status.change');
Route::get('/settings','Backend\WebInfoController@setting')->name('setting.change');

routes/frontend.php
<?php

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// redirect from register page to home page
Route::get('/admin', function () {
    return redirect('/admin/login');
});

Route::get('/run-migrate', function () {
    Artisan::call('migrate');
    return "Successfully migrated";

});
Route::get('/config-cache', function () {
    Artisan::command('logs:clear', function() {

        exec('rm ' . storage_path('logs/*.log'));

        $this->comment('Logs have been cleared!');

    })->describe('Clear log files');
    return "Successfully cleared logs";

});
Artisan::command('logs:clear', function() {

    exec('rm ' . storage_path('logs/*.log'));

    $this->comment('Logs have been cleared!');

})->describe('Clear log files');

Route::get('/clear-cache', function () {

    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('config:cache');
    Artisan::call('view:clear');
    return "Cache is cleared";
});
Route::get('/storage-link', function () {

    Artisan::call('storage:link');
    return "Storage is linked";
});


Route::get('/comming-soon', 'frontend\FrontendController@commingSoon')->name('frontend.comming.soon');
Route::get('/', 'frontend\FrontendController@index')->name('frontend.home');

/*about*/
Route::get('/about', 'frontend\FrontendController@about')->name('frontend.about');

/*services*/
Route::get('/services', 'frontend\FrontendController@service')->name('frontend.service');
Route::get('/service-detail/{id}', 'frontend\FrontendController@serviceDetail')->name('frontend.service-detail');

/*Rating*/
Route::get('/ratings', 'frontend\FrontendController@ratings')->name('frontend.ratings');
Route::get('/ratings/search', 'frontend\FrontendController@ratingsSearch')->name('frontend.ratingsSearch');
Route::get('/rating-details/{id}', 'frontend\FrontendController@ratingsDetails')->name('frontend.ratingsDetail');

/*Press Release*/
Route::get('/press-release', 'frontend\FrontendController@pressRelease')->name('frontend.pressRelease');
Route::get('/press-release-detail/{id}', 'frontend\FrontendController@pressReleaseDetail')->name('frontend.pressReleaseDetail');

/*Career*/
Route::get('/career', 'frontend\FrontendController@careers')->name('frontend.career');
Route::get('/career-details/{id}', 'frontend\FrontendController@careerDetail')->name('frontend.career.detail');
Route::get('/career-apply', 'frontend\FrontendController@careerApply')->name('frontend.career.apply');
Route::post('/career-apply', 'Backend\CareerAppliesController@store')->name('frontend.career.apply.new');

/*Contact*/
Route::get('/contact', 'frontend\FrontendController@contact')->name('frontend.contact');
Route::post('/contact', 'frontend\FrontendController@contactUs')->name('contact.us');


/*Fallback*/
Route::fallback(function() {
    return view('nopage');
});

app/Http/Controllers/Backend/SliderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Model\Slider;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $data['sliders'] = Slider::latest()->get();
        return view('backend.partials.slider.slider',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        $image = $request->file('slider_image');
        $file = New Slider();

        $imageName = time() . ('.' . $image->getClientOriginalExtension());
        $image->move(public_path('images/slider'), $imageName);
        $file->create([
            'slider_image' => $imageName,
            'title' => $request['title'],
            'description' => $request['description'],
            'button_name' => $request['button_name'],
            'url_link' => $request['url_link'],
            'status' => true,

        ]);
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function show(slider $slider)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function edit(slider $slider)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $image = $request->file('slider_image');
        $file = Slider::find($id);
        $path = public_path() . '/images/slider/' . $file['slider_image'];
        if ($image) {
            if(isset($file['slider_image'])) {
                unlink($path);
            }
            $imageName = time() . ('.'.$image->getClientOriginalExtension());
            $image->move(public_path('images/slider'), $imageName);
        } else {
            $imageName = $file['slider_image'];
        }
        $file->update([
            'slider_image' => $imageName,
            'title' => $request['title'],
            'description' => $request['description'],
            'button_name' => $request['button_name'],
            'url_link' => $request['url_link'],
        ]);
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $slider = Slider::find($id);
      $path = public_path('/images/slider/' . $slider['image']);
      if(isset($slider['image'])) {
        unlink($path);
    }        
    $slider->delete();
    return redirect()->back();
}
}

resources/views/backend/partials/slider/add.blade.php
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
style="display: none;">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4>Add Slider</h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        </div>
        <div class="modal-body">
            <form method="POST" action="{{route('slider.store')}}" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="form-group">
                    <label for="exampleInputFile">Select Image</label>
                    <input type="file" value="{{old('slider_image')}}" name="slider_image" id="exampleInputFile" required>
                    <p class="help-block">File Must Be In Image Format. Insert Image of 3 X 2</p>
                </div>
                <div class="form-group">
                    <label for="title">Slider Title</label>
                    <input type="text" value="{{old('title')}}" name="title" class="form-control" id="title"
                    placeholder="Enter Title" required>
                </div>
                <div class="form-group">
                    <label for="description">Slider Description</label>
                    <textarea name="description" value="{{old('description')}}" class="form-control"
                    id="description" cols="5" rows="10"></textarea>
                </div>
                <div class="form-group">
                    <label for="title">Button Name</label>
                    <input type="text" value="{{old('button_name')}}" name="button_name" class="form-control" id="buttonname" placeholder="Enter Button Name" required>
                </div>
                <div class="form-group">
                    <label for="title">Button URL</label>
                    <input type="text" value="{{old('url_link')}}" name="url_link" class="form-control" id="url_link" placeholder="Enter button url" required>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div>

resources/views/backend/partials/slider/edit.blade.php
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Edit Slider</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{route('slider.update',['slider'=>$slider['id']])}}" enctype="multipart/form-data">
                    {{method_field('patch')}}
                    {{csrf_field()}}
                    <div class="form-group">
                        <label for="Image_input">Select Image</label>
                        <input type="file" name="slider_image" >
                        <p class="help-block">File Must Be In Image Format. Insert Image of 3 X 2</p>
                    </div>
                    <div class="form-group">
                        <label for="title">slider Title</label>
                        <input type="text" name="title" value="{{$slider['title']}}" class="form-control" placeholder="Enter Title">
                    </div>
                    <div class="form-group">
                        <label for="description">slider Description</label>
                        <textarea name="description" class="form-control" cols="5" rows="10">{{$slider['description']}}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="title">Button Name</label>
                        <input type="text" value="{{$slider['button_name']}}" name="button_name" class="form-control"  placeholder="Enter Button Name" required>
                    </div>
                    <div class="form-group">
                        <label for="title">Button URL</label>
                        <input type="text" value="{{$slider['url_link']}}" name="url_link" class="form-control"  placeholder="Enter button url" required>
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

resources/views/backend/partials/slider/slider.blade.php
@extends('backend.layouts.app')
@section('content')
    <div class="banner">
        <h2>
            <a href="/admin/home">Home</a>
            <i class="fa fa-angle-right"></i>
            <span>Slider</span>
        </h2>
    </div>
    <!--//banner-->
    <!--faq-->
    <div class="blank">


        <div class="blank-page">

            <div class="grid_3 grid_5">
                <div class="bs-example2 bs-example-padded-bottom">
                    <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#addModal">
                        Add Slider
                    </button>
                </div>
                @include('backend.partials.slider.add')
            </div>
            <table class="table" id="datatable">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Image</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Button Name</th>
                    <th scope="col">Button link</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($sliders as $slider)
                    <tr>

                        <th scope="row">{{$loop->iteration}}</th>
                        <td>
                            <div class="col-md">
                                <div class="gallery-img">
                                    <a href="{{asset('images/slider/'.$slider['slider_image'])}}"
                                       class="b-link-stripe b-animate-go  swipebox" title="Image Title">
                                        <img class="img-responsive" src="{{asset('images/slider/'.$slider['slider_image'])}}" alt="">
                                        <span class="zoom-icon"> </span> </a>

                                </div>
                            </div>
                        </td>
                        <td>{{$slider['title']}}</td>
                        <td> @if(strlen($slider['description'])>300)
                                {!! substr($slider['description'],0,strpos($slider['description'],".",300))!!}
                            @else
                                {!!$slider['description']!!}
                            @endif</td>
                            <td>{{$slider['button_name']}}</td>
                            <td><a target="_blank" href="{{$slider['url_link']}}">{{$slider['url_link']}}</a></td>
                        <td><button data-toggle="modal" data-target="#editModal{{$slider['id']}}">
                                <i class="fa fa-pencil-square text-primary fa-2x"></i>
                            </button>&ensp;&ensp;
                            <form action="{{ route('slider.destroy', ['slider'=>$slider['id']]) }}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button onclick="return confirm('Are you sure you want to delete?')">  <i class="fa fa-trash text-danger fa-2x"></i></button>
                            </form>
                           </td>
                        <div class="modal fade" id="editModal{{$slider['id']}}" tabindex="-1" role="dialog"
                             aria-labelledby="myModalLabel"
                             aria-hidden="true" style="display: none;">
                            @include('backend.partials.slider.edit')
                        </div>

                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>

@endsection