routes/backend.php
<?php

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');
Route::resource('image', 'Backend\ImageController');
Route::resource('video', 'Backend\VideoController');
Route::resource('press-release', 'Backend\EventController');
Route::resource('contacts', 'Backend\ContactController');
Route::resource('management', 'Backend\ManagementController');
Route::resource('expert', 'Backend\ExpertController');
Route::resource('institutional', 'Backend\InstitutionalController');
Route::resource('category', 'Backend\CategoryController');
Route::resource('blog', 'Backend\BlogController');
Route::resource('testimonial', 'Backend\TestimonialController');
Route::resource('slider', 'Backend\SliderController');
Route::resource('rating', 'Backend\RatingController');
Route::get('/rating/status/{id}','Backend\RatingController@statusChange')->name('rating.status.change');
Route::resource('service', 'Backend\ServiceController');
Route::resource('webinfo', 'Backend\WebInfoController');
Route::get('/career/info','Backend\WebInfoController@career')->name('webinfo.career');
Route::resource('career', 'Backend\CareerController');
Route::resource('career-applicant', 'Backend\CareerAppliesController');
Route::post('/career-applicant/status/','Backend\CareerAppliesController@statusUpdate')->name('career-applicant.status.change');
Route::post('/career/sort','Backend\CareerController@sort')->name('career.sort');
Route::get('/career/status/{id}','Backend\CareerController@statusChange')->name('career.status.change');
Route::get('/settings','Backend\WebInfoController@setting')->name('setting.change');

routes/frontend.php
<?php

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// redirect from register page to home page
Route::get('/admin', function () {
    return redirect('/admin/login');
});

Route::get('/run-migrate', function () {
    Artisan::call('migrate');
    return "Successfully migrated";

});
Route::get('/config-cache', function () {
    Artisan::command('logs:clear', function() {

        exec('rm ' . storage_path('logs/*.log'));

        $this->comment('Logs have been cleared!');

    })->describe('Clear log files');
    return "Successfully cleared logs";

});
Artisan::command('logs:clear', function() {

    exec('rm ' . storage_path('logs/*.log'));

    $this->comment('Logs have been cleared!');

})->describe('Clear log files');

Route::get('/clear-cache', function () {

    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('config:cache');
    Artisan::call('view:clear');
    return "Cache is cleared";
});
Route::get('/storage-link', function () {

    Artisan::call('storage:link');
    return "Storage is linked";
});


Route::get('/comming-soon', 'frontend\FrontendController@commingSoon')->name('frontend.comming.soon');
Route::get('/', 'frontend\FrontendController@index')->name('frontend.home');

/*about*/
Route::get('/about', 'frontend\FrontendController@about')->name('frontend.about');

/*services*/
Route::get('/services', 'frontend\FrontendController@service')->name('frontend.service');
Route::get('/service-detail/{id}', 'frontend\FrontendController@serviceDetail')->name('frontend.service-detail');

/*Rating*/
Route::get('/ratings', 'frontend\FrontendController@ratings')->name('frontend.ratings');
Route::get('/ratings/search', 'frontend\FrontendController@ratingsSearch')->name('frontend.ratingsSearch');
Route::get('/rating-details/{id}', 'frontend\FrontendController@ratingsDetails')->name('frontend.ratingsDetail');

/*Press Release*/
Route::get('/press-release', 'frontend\FrontendController@pressRelease')->name('frontend.pressRelease');
Route::get('/press-release-detail/{id}', 'frontend\FrontendController@pressReleaseDetail')->name('frontend.pressReleaseDetail');

/*Career*/
Route::get('/career', 'frontend\FrontendController@careers')->name('frontend.career');
Route::get('/career-details/{id}', 'frontend\FrontendController@careerDetail')->name('frontend.career.detail');
Route::get('/career-apply', 'frontend\FrontendController@careerApply')->name('frontend.career.apply');
Route::post('/career-apply', 'Backend\CareerAppliesController@store')->name('frontend.career.apply.new');

/*Contact*/
Route::get('/contact', 'frontend\FrontendController@contact')->name('frontend.contact');
Route::post('/contact', 'frontend\FrontendController@contactUs')->name('contact.us');


/*Fallback*/
Route::fallback(function() {
    return view('nopage');
});

app/Http/Controllers/Backend/BlogController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Model\Blog;
use App\Model\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $blogs = Blog::orderBy('created_at', 'desc')->get();
        $categories = Category::orderBy('created_at', 'desc')->get();
        return view('backend.partials.blog.blog')->with(['blogs' => $blogs, 'categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $image = $request->file('image');
        $file = New Blog();

        $imageName = time() . ('.' . $image->getClientOriginalExtension());
        $image->move(public_path('images/blog'), $imageName);
        $file->create([
            'image' => $imageName,
            'category_id' => $request['category'],
            'author_name' => $request['author_name'],
            'title' => $request['title'],
            'description' => $request['description'],
            'status' => true,

        ]);
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $image = $request->file('image');
        $file = Blog::find($id);
        $path = public_path() . '/images/blog/' . $file['image'];
        if ($image) {
            if(isset($file['image'])) {
                unlink($path);
            }
            $imageName = time() . ('.'.$image->getClientOriginalExtension());
            $image->move(public_path('images/blog'), $imageName);
        } else {
            $imageName = $file['image'];
        }


        $file->update([
            'image' => $imageName,
            'author_name' => $request['author_name'],
            'category_id' => $request['category'],
            'title' => $request['title'],
            'description' => $request['description'],
        ]);
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $blog = Blog::find($id);
        $path = public_path('/images/blog/' . $blog['image']);
        if(isset($blog['image'])) {
            unlink($path);
        }        $blog->delete();
        return redirect()->back();
    }
}

resources/views/backend/partials/blog/add.blade.php
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
     style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Add Events And News</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{route('blog.store')}}" enctype="multipart/form-data">
                    {{csrf_field()}}
                    <div class="form-group">
                        <label for="exampleInputFile">Select Image</label>
                        <input type="file" value="{{old('image')}}" name="image" id="exampleInputFile" required>
                        <p class="help-block">File Must Be In Image Format. Insert Image of 3 X 2</p>
                    </div>
                    <div class="form-group">
                        <label for="category">Category</label>
                        <select name="category" class="form-control" id="">
                            <option value="" selected disabled>Select Category</option>
                            @foreach($categories as $category)
                                <option value="{{$category['id']}}">{{$category['title']}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="title">Author Name</label>
                        <input type="text" value="{{old('author_name')}}" name="author_name" class="form-control" id="title"
                               placeholder="Enter Title" required>
                    </div>
                    <div class="form-group">
                        <label for="title">Blog Title</label>
                        <input type="text" value="{{old('title')}}" name="title" class="form-control" id="title"
                               placeholder="Enter Title" required>
                    </div>
                    <div class="form-group">
                        <label for="description">Blog Description</label>
                        <textarea name="description" value="{{old('description')}}" class="form-control"
                                  id="description" cols="5" rows="10"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

resources/views/backend/partials/blog/blog.blade.php
@extends('backend.layouts.app')
@section('content')
    <div class="banner">
        <h2>
            <a href="/admin/home">Home</a>
            <i class="fa fa-angle-right"></i>
            <span>Blogs</span>
        </h2>
    </div>
    <!--//banner-->
    <!--faq-->
    <div class="blank">


        <div class="blank-page">

            <div class="grid_3 grid_5">
                <div class="bs-example2 bs-example-padded-bottom">
                    <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#addModal">
                        Add Blog
                    </button>
                </div>
                @include('backend.partials.blog.add')
            </div>
            <table class="table" id="datatable">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Image</th>
                    <th scope="col">Category</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($blogs as $blog)
                    <tr>

                        <th scope="row">1</th>
                        <td>
                            <div class="col-md">
                                <div class="gallery-img">
                                    <a href="{{asset('images/blog/'.$blog['image'])}}"
                                       class="b-link-stripe b-animate-go  swipebox" title="Image Title">
                                        <img class="img-responsive" src="{{asset('images/blog/'.$blog['image'])}}" alt="">
                                        <span class="zoom-icon"> </span> </a>

                                </div>
                            </div>
                        </td>
                        <td>{{$blog->category['title']}}</td>
                        <td>{{$blog['title']}}</td>
                        <td> @if(strlen($blog['description'])>300)
                                {!! substr($blog['description'],0,strpos($blog['description'],".",300))!!}
                            @else
                                {!!$blog['description']!!}
                            @endif</td>
                        <td><button data-toggle="modal" data-target="#editModal{{$blog['id']}}">
                                <i class="fa fa-pencil-square text-primary fa-2x"></i>
                            </button>&ensp;&ensp;
                            <form action="{{ route('blog.destroy', ['blog'=>$blog['id']]) }}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button onclick="return confirm('Are you sure you want to delete?')">  <i class="fa fa-trash text-danger fa-2x"></i></button>
                            </form>
                           </td>
                        <div class="modal fade" id="editModal{{$blog['id']}}" tabindex="-1" role="dialog"
                             aria-labelledby="myModalLabel"
                             aria-hidden="true" style="display: none;">
                            @include('backend.partials.blog.edit')
                        </div>

                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>

@endsection

resources/views/backend/partials/blog/edit.blade.php
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Edit Events And News</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{route('blog.update',['blog'=>$blog['id']])}}" enctype="multipart/form-data">
                    {{method_field('patch')}}
                    {{csrf_field()}}
                    <div class="form-group">
                        <label for="exampleInputFile">Select Image</label>
                        <input type="file" name="image" id="exampleInputFile">
                        <p class="help-block">File Must Be In Image Format. Insert Image of 3 X 2</p>
                    </div>
                    <div class="form-group">
                        <label for="category">Category</label>
                        <select name="category" class="form-control" id="">
                            <option value="{{$blog->category['id']}}" selected>{{$blog->category['title']}}</option>
                            @foreach($categories as $category)
                                <option value="{{$category['id']}}">{{$category['title']}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="title">Author Name</label>
                        <input type="text" value="{{$blog['author_name']}}" name="author_name" class="form-control" id="title"
                               placeholder="Enter Title" required>
                    </div>
                    <div class="form-group">
                        <label for="title">Blog Title</label>
                        <input type="text" name="title" value="{{$blog['title']}}" class="form-control" id="title" placeholder="Enter Title">
                    </div>
                    <div class="form-group">
                        <label for="description">Blog Description</label>
                        <textarea name="description" class="form-control" id="description" cols="5" rows="10">{{$blog['description']}}</textarea>
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->